version: '3.8'

services:
  backend:
    build: ./backend
    container_name: compliance-backend
    ports:
      - "3001:3001"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend/src/uploads:/app/src/uploads
      - ./backend/src/cloud_outputs:/app/src/cloud_outputs
    depends_on:
      - qdrant

  qdrant:
    image: qdrant/qdrant
    container_name: compliance-qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage

volumes:
  qdrant_data:
