version: '3.8'

services:
  backend:
    build: .
    container_name: compliance-backend
    ports:
      - "3001:3001"
    env_file:
      - backend/.env
    volumes:
      - ./backend/uploads:/app/uploads
      - ./backend/cloud_outputs:/app/cloud_outputs
  #   depends_on:
  #     - mongo

  # mongo:
  #   image: mongo:6
  #   container_name: compliance-mongo
  #   ports:
  #     - "27017:27017"
  #   volumes:
  #     - mongodb_data:/data/db

# volumes:
#   mongodb_data: