version: '3.8'

services:
  app:
    build: .
    container_name: flask-app
    ports:
      - "3030:3030"
    volumes:
      - .:/app
    depends_on:
      - ollama
      - qdrant

  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama

  qdrant:
    image: qdrant/qdrant
    container_name: qdrant
    ports:
      - "6333:6333"
    volumes:
      - qdrant-data:/qdrant/storage

volumes:
  ollama-data:
  qdrant-data:
